#!/bin/bash

if [[ "$(basename $(pwd))" == "igniter" ]]; then
    cd ..
    ./switch-branch-migrate "$@"
    cd igniter
    exit
fi

branch_name=$1

cd igniter

if git show-ref --verify --quiet refs/heads/"$branch_name"; then
    git checkout "$branch_name"
else
    git checkout -b "$branch_name"
fi

cd ..

docker compose exec app php spark # migrate
